import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "./components/NavBar";


export const metadata: Metadata = {
  title: "Leitura de Nutrientes",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br">
      <body>
        <NavBar/>
        <main>{children}</main>
      </body>
    </html>
  );
}
