import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Leitura de Nutrientes",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br">
      <body>
        {children}
      </body>
    </html>
  );
}
